#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/HW5980_2.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar" HW5980_2 "$@"
